version: '3.8'

services:
  apache-server:
    image: httpd:alpine
    container_name: apache-server
    ports:
      - "8082:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    networks:
      - my-network

networks:
  my-network:
    driver: bridge