version: '3.8'

services:

  apache-server:
    image: httpd:alpine
    container_name: apache-server
    ports:
      - "8082:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    networks:
      - my-network
    platform: linux/amd64

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my-network
    platform: linux/amd64

  custom-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: custom-app
    environment:
      DB_HOST: mysql-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: app_db
    ports:
      - "5001:5001"
    depends_on:
      - mysql-db
    networks:
      - my-network
    platform: linux/amd64

networks:
  my-network:
    driver: bridge
  jenkins-network:
    driver: bridge
