version: '3.8'

services:
  apache-server:
    image: httpd:alpine
    container_name: apache-server
    ports:
      - "8082:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs
    networks:
      - app-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge